### ISSUE TITLE
systemd service on ubuntu

### ISSUE THREAD

**Issue by elbowz** [troyengel/petrified#4]
I think a little bug...

On ubuntu I have to change _petrified.service_ from:

`ExecStart=/usr/bin/petrified -c /etc/petrified.conf`

to:
`ExecStart=/usr/local/bin/petrified -c /etc/petrified.conf`

**Comment by troyengel** [comment]
The unit is designed to be put into place by packagers, whereby the executable will go into /usr/bin but I guess we could do something in the Makefile to create these units. It's not really a bug. but more or a design problem when used outside of packaging. The same is true for the config, technically if you're using /usr/local then it belongs in /usr/local/etc.

**Comment by troyengel** [comment]
Yeah OK what we'll need to do it seems:

* convert the units to .in variants and create variables within them for the path elements
* add logic on "make" to run... sed? (seems logical) or somesuch to do a replacement on the fly
* update the code itself (see CONF_GLOBAL) to do the same thing, however we could just add extra logic to check /etc/ and /usr/local/etc without having to play the .in game with a shell script

I'll see if I can get to it this weekend, doesn't seem too hard. :)

**Comment by elbowz** [comment]
I don't understand well what you have said but it seems cool :)

Could you also add a -verbosity option or a -silent one, it's annoying always is in the systemd log: "IP [...] hasn't changed, not updating"

thanks

**Comment by troyengel** [comment]
Partial fix - I added a new 'LOG_QUIET' in the config file that will suppress the logging if the IP has not changed. While I was in there I also enhanced the error checking of the return values from upstream to prevent updating the PET_LIP file when getting a bad response (404, etc.)

It's in the 'devel' branch and requires you convert your domain to API v2 now (https://freedns.afraid.org/dynamic/v2/) which will be the 2.x release soon-ish.

**Comment by troyengel** [comment]
Wasn't ready for this to close with that commit...

**Comment by troyengel** [comment]
OK now we can close this -- I have used proper templates to generate the systemd unit 'ExexStart=' bin directory by the Makefile. The units needed a revamp for 2017, they've been converted to using the default "timers.target" available in systemd, vastly simplifying things - our own 'petrified.target' is gone, over complicated.

Commit which did this: https://github.com/troyengel/petrified/commit/1ef76d3e401b5691a5c9d754755539f76dd747e3

I'll get this released out of devel to Master soon-ish.
