### ISSUE TITLE
Support dynamic update version 2

### ISSUE THREAD

**Issue by mestaritonttu** [troyengel/petrified#5]
http://freedns.afraid.org/dynamic/v2/

As a brute force modification, I tweaked the script like so:
```
DDNS_URL=http://sync.afraid.org/u/

UPDURL="${DDNS_URL}${DDNS_KEY}/"
```

It seemed to work.

Thanks for your efforts!

**Comment by troyengel** [comment]
Sorry it's taken me so long -- I can't seem to actually find docs that outline what the new URL pattern is supposed to be, your example above seems to be undocumented. I've emailed Josh for help on his new API, it's not clearly written how it works.

**Comment by troyengel** [comment]
Hi @mestaritonttu - I just pushed a new commit which implements v2 API on the 'devel' branch, if you'd like to give it a try before I release it; you should be able to just grab the shell script, the rest of the commit was paperworrk (README, etc.). This will be released as a new 2.x version for API v2. :)

https://github.com/troyengel/petrified/blob/devel/petrified

Lemme know how it goes, it's basically just what you did but including the IP for intranet users (private IPs).

**Comment by mestaritonttu** [comment]
Thank you very much! I grabbed your new version and started using it.

**Comment by troyengel** [comment]
@mestaritonttu - I had a nice email exchange with Josh (owner of FreeDNS), a new version is in 'devel' that tries to autodetect API v1 or API v2 based on your key in the config file. If you have time, help test my new code version :)   https://github.com/troyengel/petrified/blob/devel/petrified

This so when I release a new version of petrified, it won't break the users who have not upgraded to the API v2 yet and still have API v1 keys used.

**Comment by mestaritonttu** [comment]
Was at a conference so could not reply sooner. I started using the devel version yesterday and seems to be working so far!
